openapi: "3.0.2"
info:
  title: Authentification
  description: Api pour la gestion de l'authentification et des identités dans le projet Astéroïde Warrior
  version: "1.0"
servers:
  - url: https://auth.aw.alexandre-vogel.fr/

tags:
  - name: Authentification
    description: Action relative à l'authentification d'un utilisateur
  - name: Token
    description: Action liée au token
  - name: Serveurs
    description: Action liée aux serveurs
  - name: BDD
    description: Action liée à la base de donnée
  - name: Admin
    description: Action liée aux privilèges
  - name: Ban
    description: Action liée au banissement d'un utilisateur

paths:
  /user/login:
    post:
      tags:
        - Authentification
      summary: Connect un utilisateur
      description: Permet à un utilisateur de se connecter et renvois un tokent pour l'identifier
      requestBody:
        description: Demande de connexion de l'utilisateur `MyUser`
        content:
          json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: MyUser
                  description: Nom unique de l'utilisateur
                password:
                  type: string
                  example: MyPassword
                  description: Mot de passe de l'utilisateur
      responses:
        "200":
          description: Connexion reussi
          content:
            json:
              schema:
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: "4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55"
                    description: Token utilisable par l'utilisateur pour s'identifier
        "400":
          description: Nom d'utilisateur / mot de passe non valide

  /user/check:
    post:
      tags:
        - Token
      summary: Vérifie le Token d'un utilisateur
      description: Vérifie le `Token` d'un utilisateur, et renvois les informations liées à l'utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - token
              properties:
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'utilisateur
      responses:
        "200":
          description: Information sur l'utilisateur
          content:
            json:
              schema:
                required:
                  - name
                  - role
                properties:
                  name:
                    type: string
                    example: MyUser
                    description: Nom de l'utilisateur
                  role:
                    type: string
                    example: S
                    description: Rôle de l'utilisateur
        "400":
          description: Token non valide

  /server/add:
    post:
      tags:
        - Serveurs
      summary: Ajoute un nouveau serveur
      description: Permet à un administrateur d'ajouter un nouveau server
      requestBody:
        content:
          json:
            schema:
              required:
                - user_token
                - name
              properties:
                user_token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
                name:
                  type: string
                  example: MonSuperServeur
                  description: Nom du nouveau serveur
      responses:
        "200":
          description: Token pour le serveur
          content:
            json:
              schema:
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: 7dea256198bb51e501ee2d18da735a006e85ef00d6fde30dbd4c141490db9dc8
                    description: Token pour identifier le serveur
        "401":
          description: Token utilisateur non valide
        "400":
          description: Le serveur existe déja
  
  /server/check:
    post:
      tags:
        - Token
        - Serveurs
      summary: Vérifie le Token d'un serveur
      description: Vérifie le `Token` d'un serveur, et renvois les informations liées au serveur
      requestBody:
        content:
          json:
            schema:
              required:
                - token
              properties:
                token:
                  type: string
                  example: 7dea256198bb51e501ee2d18da735a006e85ef00d6fde30dbd4c141490db9dc8
                  description: Token du serveur
      responses:
        "200":
          description: Information sur le serveur
          content:
            json:
              schema:
                required:
                  - name
                properties:
                  name:
                    type: string
                    example: MonSuperServeur
                    description: Nom du serveur
        "400":
          description: Token non valide

  /user/add:
    post:
      tags:
        - Authentification
        - BDD
      summary: Ajoute un utilisateur
      description: Enregistre un utilisateur dans la base de donnée
      requestBody:
        content:
          json:
            schema:
              required:
                - username
                - password
                - email
              properties:
                username:
                  type: string
                  example: user1
                  description: Nom unique de l'utilisateur
                password:
                  type: string
                  example: pwd
                  description: Mot de passe de l'utilisateur
                email:
                  type: string
                  example: email@email.email       
                  description: Email unique de l'utilisateur
      responses:
        "200":
          description: Ajout de l'utilisateur réussi
          content: 
            json:
              schema:
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: 7dea256198bb51e501ee2d18da735a006e85ef00d6fde30dbd4c141490db9dc8
                    description: Token pour identifier l'utilisateur
        "400":
          description: Nom d'utilisateur non valide
        "401":
          description: L'utilisateur existe déjà

  /user/admin:
    post:
      tags:
        - Admin
      summary: Ajoute un administrateur
      description: Donne à un utilisateur les droits d'administrateur
      requestBody:
        content:
          json:
            schema:
              required:
                - username
              properties:
                username:
                  type: string
                  example: MyUser
                  description: Nom unique de l'utilisateur
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
      responses:
        "200":
          description: Attribution des droits d'administrateur réussie
        "400":
          description: Nom d'utilisateur non valide
        "401":
          description: L'utilisateur est déjà administrateur
  
  /user/unadmin:
    post:
      tags:
        - Admin
      summary: Baisse les privilèges
      description: Retire les privilèges à un utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - username
              properties:
                username:
                  type: string
                  example: MyUser
                  description: Nom unique de l'utilisateur
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
      responses:
        "200":
          description: Retrait des privilèges réussi
        "400":
          description: Nom d'utilisateur non valide
        "401":
          description: Les privilèges d'un utilisateur sont déjà limités

  /user/ban:
    post:
      tags:
        - Ban
        - Token
        - Admin
      summary: Bannissement d'un utilisateur
      description: Permet le banissement d'un utilisateur par un administrateur
      requestBody:
        content:
          json:
            schema:
              required:
                - username
                - token
              properties:
                username:
                  type: string
                  example: MyUser
                  description: Nom de l'utilisateur à bannir
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
      responses:
        "200":
          description: Bannissement réussi
        "400":
          description: Nom d'utilisateur non valide
        "401":
          description: L'utilisateur est déjà banni
        "402":
          description: Token non valide

  /user/unban:
    post:
      tags:
        - Ban
        - Admin
        - BDD
      summary: Lève la suspension
      description: Permet à un administrateur de lever la suspension à un utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - username
              properties:
                username:
                  type: string
                  example: MyUser
                  description: Nom unique de l'utilisateur
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
      responses:
        "200":
          description: Suspension levé 
        "400":
          description: Token non valide
        "401":
          description: Nom d'utilisateur non valide
        "402":
          description: L'utilisateur n'est pas banni

  /user/remove:
    post:
      tags:
        - Admin
        - Token
      summary: Retire un utilisateur
      description: Permet à un administrateur de retirer un utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - username
                - token
              properties:
                username:
                  type: string
                  example: MyUser
                  description: Nom de l'utilisateur à retirer
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
      responses:
        "200":
          description: Utilisateur retiré
        "400":
          description: Token non valide
        "401":
          description: Nom d'utilisateur non valide
  
  /server/remove:
    post:
      tags:
        - Admin
        - Serveurs
      summary: Retire un serveur
      description: Permet à un administrateur de retirer un serveur
      requestBody:
        content:
          json:
            schema:
              required:
                - name
                - token
              properties:
                name:
                  type: string
                  example: MonSuperServeur
                  description: Nom du serveur à retirer
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
      responses:
        "200":
          description: Serveur retiré
        "400":
          description: Token non valide
        "401":
          description: Nom du serveur non valide