openapi: "3.0.2"
info:
  title: Authentification
  description: Api pour la gestion de l'authentification et des identités dans le projet Astéroïde Warrior
  version: "1.0"
servers:
  - url: https://auth.aw.alexandre-vogel.fr/

tags:
  - name: Authentification
    description: Action relative à l'Authentification d'un utilisateur
  - name: Token
    description: Action liée au token

paths:
  /user/login:
    post:
      tags:
        - Authentification
      summary: Connect un utilisateur
      description: Permet à un utilisateur de se connecter et renvois un tokent pour l'identifier
      parameters:
        - in: header
          name: username
          schema:
            type: string
          required: true
          description: Nom unique de l'utilisateur
        - in: header
          name: password
          schema:
            type: string
          required: true
          description: Mot de passe de l'utilisateur
      requestBody:
        description: Demande de connexion de l'utilisateur `MyUser`
        content:
          json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: MyUser
                password:
                  type: string
                  example: MyPassword
      responses:
        "200":
          description: Connexion reussi
          headers:
            tokent:
              description: Token utilisable par l'utilisateur pour s'identifier
              schema:
                type: string
          content:
            json:
              schema:
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: "4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55"
        "400":
          description: Nom d'utilisateur / mot de passe non valide

  /user/check:
    post:
      tags:
        - Token
      summary: Vérifie le Token d'un utilisateur
      description: Vérifie le `Token` d'un utilisateur, et renvois les informations liées à l'utilisateur
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
          description: Token de l'utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - token
              properties:
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
      responses:
        "200":
          description: Information sur l'utilisateur
          headers:
            name:
              description: Nom de l'utilisateur
              schema:
                type: string
            role:
              description: Rôle de l'utilisateur
              schema:
                type: string
          content:
            json:
              schema:
                required:
                  - name
                  - role
                properties:
                  name:
                    type: string
                    example: MyUser
                  role:
                    type: string
                    example: S
        "400":
          description: Token non valide
