openapi: "3.0.2"
info:
  title: Authentification
  description: Api pour la gestion de l'authentification et des identités dans le projet Astéroïde Warrior
  version: "1.0"
servers:
  - url: https://auth.aw.alexandre-vogel.fr/

tags:
  - name: Authentification
    description: Action relative à l'Authentification d'un utilisateur
  - name: Token
    description: Action liée au token
  - name: Serveurs
    description: Action liée aux serveurs

paths:
  /user/login:
    post:
      tags:
        - Authentification
      summary: Connect un utilisateur
      description: Permet à un utilisateur de se connecter et renvois un tokent pour l'identifier
      requestBody:
        description: Demande de connexion de l'utilisateur `MyUser`
        content:
          json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: MyUser
                  description: Nom unique de l'utilisateur
                password:
                  type: string
                  example: MyPassword
                  description: Mot de passe de l'utilisateur
      responses:
        "200":
          description: Connexion reussi
          content:
            json:
              schema:
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: "4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55"
                    description: Token utilisable par l'utilisateur pour s'identifier
        "400":
          description: Nom d'utilisateur / mot de passe non valide

  /user/check:
    post:
      tags:
        - Token
      summary: Vérifie le Token d'un utilisateur
      description: Vérifie le `Token` d'un utilisateur, et renvois les informations liées à l'utilisateur
      requestBody:
        content:
          json:
            schema:
              required:
                - token
              properties:
                token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'utilisateur
      responses:
        "200":
          description: Information sur l'utilisateur
          headers:
            name:
              description: Nom de l'utilisateur
              schema:
                type: string
            role:
              description: Rôle de l'utilisateur
              schema:
                type: string
          content:
            json:
              schema:
                required:
                  - name
                  - role
                properties:
                  name:
                    type: string
                    example: MyUser
                  role:
                    type: string
                    example: S
        "400":
          description: Token non valide

  /server/add:
    post:
      tags:
        - Serveurs
      summary: Ajoute un nouveau serveur
      description: Permet à un administrateur d'ajouter un nouveau server
      requestBody:
        content:
          json:
            schema:
              required:
                - user_token
                - name
              properties:
                user_token:
                  type: string
                  example: 4c3769786e6614e562a1602847c15712761eb68e4f1609a60c4f7ad064382d55
                  description: Token de l'administrateur
                name:
                  type: string
                  example: MonSuperServeur
                  description: Nom du nouveau serveur
      responses:
        "200":
          description: Token pour le serveur
          content:
            json:
              schema:
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: 7dea256198bb51e501ee2d18da735a006e85ef00d6fde30dbd4c141490db9dc8
                    description: Token pour identifier le serveur
        "401":
          description: Token utilisateur non valide
        "400":
          description: Le serveur existe déja
  
  /server/check:
    post:
      tags:
        - Token
        - Serveurs
      summary: Vérifie le Token d'un serveur
      description: Vérifie le `Token` d'un serveur, et renvois les informations liées au serveur
      requestBody:
        content:
          json:
            schema:
              required:
                - token
              properties:
                token:
                  type: string
                  example: 7dea256198bb51e501ee2d18da735a006e85ef00d6fde30dbd4c141490db9dc8
                  description: Token du serveur
      responses:
        "200":
          description: Information sur le serveur
          content:
            json:
              schema:
                required:
                  - name
                properties:
                  name:
                    type: string
                    example: MonSuperServeur
                    description: Nom du serveur
        "400":
          description: Token non valide